services:
  backend:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
    ports:
      - "5001:5000"
    env_file:
      - .flaskenv
    volumes:
      - ./secrets:/app/secrets:ro
      - ./instance:/app/instance
      - ./data:/app/data
    command: >
      sh -c "sleep 2 &&
            flask init-db &&
            gunicorn -w 4 -b 0.0.0.0:5000 --timeout 120 app:app"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
